services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: laca
    image: truong11t2/laca-blog:1.0.0
    # ports:
    #  - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - laca-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - laca-data:/data/db
    ports:
      - "64000:27017"
    networks:
      - laca-network

  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - laca-network

volumes:
  laca-data:
    driver: local
networks:
  laca-network:
    name: laca-net