services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    volumes:
      - travel-blog:/data/mongodb
    image: mongo:latest
    ports:
      - "64000:27017"
volumes:
  travel-blog: